name       : eopkg-deps
version    : 1.0
release    : 1
source     :
    - https://github.com/DataDrake/eopkg-deps/archive/v1.0.tar.gz : 3d6c0a5cb8200dea9cfc86e9495aa1cea1af209674a87957f0068ca24677c1db
license    : Apache-2.0
component  : system.utils
summary    : Dependency tracking for build automation with eopkg.
description: |
    Dependency tracking for build automation with eopkg.
builddeps  :
    - pkgconfig(sqlite3)
    - git
    - golang
networking : yes
build      : |
    %make
install    : |
    %make_install
